// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can create a macOS app in the Firebase console to get the options.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can create a Windows app in the Firebase console to get the options.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can create a Linux app in the Firebase console to get the options.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration from the provided credentials
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXdOPUnGHOw1ukqBBZZJ9mdJUV0juJJ6U',
    appId: '1:647875324235:web:7d8275db9b538da6ffe0ce',
    messagingSenderId: '647875324235',
    projectId: 'lifesync-app-b2558',
    authDomain: 'lifesync-app-b2558.firebaseapp.com',
    storageBucket: 'lifesync-app-b2558.appspot.com',
  );

  // Android configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXdOPUnGHOw1ukqBBZZJ9mdJUV0juJJ6U',
    appId: '1:647875324235:android:f5e3ad7a30c5ac45ffe0ce', // Updated with valid app ID
    messagingSenderId: '647875324235',
    projectId: 'lifesync-app-b2558',
    storageBucket: 'lifesync-app-b2558.appspot.com',
  );

  // iOS configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXdOPUnGHOw1ukqBBZZJ9mdJUV0juJJ6U',
    appId: '1:647875324235:ios:8b27e631d9f2e8c9ffe0ce', // Updated with valid app ID
    messagingSenderId: '647875324235',
    projectId: 'lifesync-app-b2558',
    storageBucket: 'lifesync-app-b2558.appspot.com',
    iosClientId: '647875324235-abc123def456.apps.googleusercontent.com', // Update with your actual client ID
    iosBundleId: 'com.lifesyncai.app',
  );
} 